author="Neutrino Team"
description="""Record start, end timestamp and smid of each thread,
can be reduced to NSight Occupancy and launch__waves_per_multiprocessor"""

[sched]
position = "kernel"
datamodel = "warp:16" # every warp save 16 bytes
before = """.reg .b64 %gstart; // global start time (unit: ns)
.reg .b64 %gend;    // global end time (unit: ns)
.reg .b64 %elapsed; // thread elapsed time in u64
.reg .b32 %elapse;  // thread elapsed time in u32
mov.u64 %gstart, %globaltimer;"""
# following operationo is done only by leader thread
after = """mov.u64 %gend, %globaltimer;
sub.u64 %elapsed, %gend, %gstart; 
cvt.u32.u64 %elapse, %elapsed; // convert to u32
SAVE.u64 {%gstart}; // store start in u64 for alignment
SAVE.u32 {%elapse, %smid}; // store elapased time and core id"""