author="Neutrino Team"
description="""Experimental Support Only"""

[REGS]  # a keyword left for defining registers
gstart = { type = 'b64', scalar = true, init = 0 }
gend   = { type = 'b64', scalar = true, init = 0 }

[sched] # other names are free to be used as 
position = "kernel"
datamodel = "warp:16" # every warp save 16 bytes
before = "S_MEMREALTIME gstart; get start timestamp"
# following operationo is done only by leader thread
after = """S_MEMREALTIME gend; get end timestamp
SAVE.u64 {gstart, gend};"""