author="Neutrino Team"
description="""Record Number of Bytes of Global Memory Access
Separate sync (ld,st) and async copy (cp.async), unit in bytes
NOTE: not yet support Warp-Group MMA"""

analyze_hook = "gmem_bytes.py"

[saving]
position = "kernel"
datamodel = "thread:8"
before = """.reg .u32 %sync_bytes; // counter for tensor core op
.reg .u32 %async_bytes; // timer for tensor core op
mov.u32 %sync_bytes, 0; // don't forget init it to 0 like C :)
mov.u32 %async_bytes, 0;   // don't forget init it to 0 like C :("""
after = """SAVE.u32 {%sync_bytes, %async_bytes};"""

[sync]
position = "ld.global:st.global"
# no datamodel
before = """add.u32 %sync_bytes, %sync_bytes, BYTES;"""

[tensor_op]
position = "cp.async.ca:cp.async.cg" # don't include commit_group and wait_group :(
# no datamodel
before = """add.u32 %async_bytes, %async_bytes, IN2;"""
