author="Neutrino Team"
description="""Count number of tensor core opeator"""

[saving]
position = "kernel"
datamodel = "thread:8"
before = """.reg .u64 %counterd; // counter for tensor core op
mov.u64 %counterd, 0; // don't forget init it to 0 like C :)"""
after  = """SAVE.u64 {%counterd};""" # TODO change to u32 to save space

[tensor_op]
position = "mma.sync.aligned" # this also include wmma.mma.sync.aligned
# no datamodel
after  = """add.u64 %counterd, %counterd, 1; // add counter"""